[package]
name = "ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.3"
clap = "2.33.3"
chrono = "0.4.19"
time = "0.3.5"
